### ISSUE TITLE
THIS MODULE CREATE A BUG IN MY MAGENTO

### ISSUE THREAD

**Issue by alinolandry** [Smile-SA/magento2-module-debug-toolbar#11]
**I use Magento EE 2.3.1.

In my development environnement, I setup this module to track some bug in my Magento, When I finish, I remove this module with composer. Everything run well, after that when I make composer update or bin/magento setup:upgrade or bin/magento setup:di:compile I got this error:** 

`In ErrorHandler.php line 61:
                                                                                                                                                                                         
`  Warning: include_once(Smile/DebugToolbar/DB/Profiler.php): failed to open stream: No such file or directory in /app/vendor/magento/zendframework1/library/Zend/Loader.php on line 134  `
`
**Now in the browser, I got this :**

`Exception: Warning: include_once(Smile/DebugToolbar/DB/Profiler.php): failed to open stream: No such file or directory in /app/vendor/magento/zendframework1/library/Zend/Loader.php on line 134 in /app/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /app/vendor/magento/zendframework1/library/Zend/Loader.php(134): Magento\Framework\App\ErrorHandler->handler(2, 'include_once(Sm...', '/app/vendor/mag...', 134, Array) #1 /app/vendor/magento/zendframework1/library/Zend/Loader.php(134): include_once() #2 /app/vendor/magento/zendframework1/library/Zend/Loader.php(82): Zend_Loader::loadFile('Smile/DebugTool...', NULL, true) #3 /app/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(396): Zend_Loader::loadClass('Smile\\DebugTool...') #4 /app/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(272): Zend_Db_Adapter_Abstract->setProfiler(Array) #5 /app/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(263): Zend_Db_Adapter_Abstract->__construct(Array) #6 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\Framework\DB\Adapter\Pdo\Mysql->__construct(Object(Magento\Framework\Stdlib\StringUtils), Object(Magento\Framework\Stdlib\DateTime), Object(Magento\Framework\DB\Logger\LoggerProxy), Object(Magento\Framework\DB\SelectFactory), Array, NULL) #7 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #8 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array) #9 /app/vendor/magento/framework/DB/Adapter/Pdo/MysqlFactory.php(64): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array) #10 /app/vendor/magento/framework/Model/ResourceModel/Type/Db/Pdo/Mysql.php(74): Magento\Framework\DB\Adapter\Pdo\MysqlFactory->create('Magento\\Framewo...', Array, NULL, NULL) #11 /app/vendor/magento/module-resource-connections/DB/ConnectionAdapter/Mysql.php(54): Magento\Framework\Model\ResourceModel\Type\Db\Pdo\Mysql->getDbConnectionInstance(NULL, NULL) #12 /app/vendor/magento/framework/Model/ResourceModel/Type/Db/ConnectionFactory.php(41): Magento\ResourceConnections\DB\ConnectionAdapter\Mysql->getConnection() #13 /app/vendor/magento/framework/App/ResourceConnection/ConnectionFactory.php(24): Magento\Framework\Model\ResourceModel\Type\Db\ConnectionFactory->create(Array) #14 /app/vendor/magento/framework/App/ResourceConnection.php(147): Magento\Framework\App\ResourceConnection\ConnectionFactory->create(Array) #15 /app/vendor/magento/framework/App/ResourceConnection.php(97): Magento\Framework\App\ResourceConnection->getConnectionByName('default') #16 /app/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(328): Magento\Framework\App\ResourceConnection->getConnection('default') #17 /app/vendor/magento/framework/Model/ResourceModel/Db/Collection/AbstractCollection.php(132): Magento\Framework\Model\ResourceModel\Db\AbstractDb->getConnection() #18 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Query), Object(Magento\Staging\Model\Event\Manager\Proxy), NULL, NULL) #19 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array) #20 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Config\\...', Array) #21 /app/generated/code/Magento/Config/Model/ResourceModel/Config/Data/CollectionFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Config...', Array) #22 /app/vendor/magento/module-config/App/Config/Source/RuntimeConfigSource.php(77): Magento\Config\Model\ResourceModel\Config\Data\CollectionFactory->create() #23 /app/vendor/magento/module-config/App/Config/Source/RuntimeConfigSource.php(62): Magento\Config\App\Config\Source\RuntimeConfigSource->loadConfig() #24 /app/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Config\App\Config\Source\RuntimeConfigSource->get('') #25 /app/vendor/magento/module-config/App/Config/Type/System/Reader.php(60): Magento\Framework\App\Config\ConfigSourceAggregated->get() #26 /app/generated/code/Magento/Config/App/Config/Type/System/Reader/Proxy.php(95): Magento\Config\App\Config\Type\System\Reader->read() #27 /app/vendor/magento/module-config/App/Config/Type/System.php(402): Magento\Config\App\Config\Type\System\Reader\Proxy->read() #28 /app/vendor/magento/module-config/App/Config/Type/System.php(247): Magento\Config\App\Config\Type\System->readData() #29 /app/vendor/magento/module-config/App/Config/Type/System.php(300): Magento\Config\App\Config\Type\System->lockedLoadData(Object(Closure)) #30 /app/vendor/magento/module-config/App/Config/Type/System.php(206): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default') #31 /app/vendor/magento/module-config/App/Config/Type/System.php(180): Magento\Config\App\Config\Type\System->getWithParts('default/newreli...') #32 /app/vendor/magento/framework/App/Config.php(131): Magento\Config\App\Config\Type\System->get('default/newreli...') #33 /app/vendor/magento/framework/App/Config.php(80): Magento\Framework\App\Config->get('system', 'default/newreli...') #34 /app/vendor/magento/framework/App/Config.php(93): Magento\Framework\App\Config->getValue('newrelicreporti...', 'default', NULL) #35 /app/vendor/magento/module-new-relic-reporting/Model/Config.php(94): Magento\Framework\App\Config->isSetFlag('newrelicreporti...') #36 /app/vendor/magento/module-new-relic-reporting/Plugin/HttpPlugin.php(49): Magento\NewRelicReporting\Model\Config->isNewRelicEnabled() #37 /app/vendor/magento/framework/Interception/Interceptor.php(121): Magento\NewRelicReporting\Plugin\HttpPlugin->beforeCatchException(Object(Magento\Framework\App\Http\Interceptor), Object(Magento\Framework\App\Bootstrap), Object(Exception)) #38 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #39 /app/generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('catchException', Array, Array) #40 /app/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception)) #41 /app/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #42 {main}`

**Everything is lock in my Magento, I didn't know why, I cleaned all cache, generated/ var/ filles, Please help me to solve the problem**

**Comment by guvra** [comment]
Hello,

I guess the module was not properly uninstalled.

- Make sure the module was removed from app/etc/config.php.
- Make sure the file app/etc/env.php does not contain any reference to this module.
- Make sure the environment variable `MAGE_PROFILER` is either unset or does not reference a class of this module.
- Make sure the module was removed from the following files: composer.json, composer.lock.
  If it is still present in one of those files, you didn't uninstall it properly. You must use `composer remove --dev smile/module-debug-toolbar`.
- Make sure the directory vendor/smile/module-debug-toolbar does not exist anymore.
- Make sure ALL cache is cleared (e.g. if you use redis, flush all cache from the redis cli, not from the Magento command).
- Clear generated/code AND generated/metadata.

**Comment by alinolandry** [comment]
I check the app/etc/env.php file, I remove this line in db node:

`'profiler' => [
                    'class' => 'Smile\\DebugToolbar\\DB\\Profiler',
                    'enabled' => true
                ]`

When I did it to clean my uninstall **manually**. The problem was solve. Thank You very much.

**Comment by Axel29** [comment]
> I check the app/etc/env.php file, I remove this line in db node:
> 
> `'profiler' => [ 'class' => 'Smile\\DebugToolbar\\DB\\Profiler', 'enabled' => true ]`
> 
> When I did it to clean my uninstall **manually**. The problem was solve. Thank You very much.

Thanks for the solution, it was getting me crazy I couldn't uninstall this module...
