### ISSUE TITLE
error with pagecache render request

### ISSUE THREAD

**Issue by onlinebizsoft** [Smile-SA/magento2-module-debug-toolbar#17]
When we have a block with _privateScope enabled the page will have a ajax pagecache request
Something like this

........./page_cache/block/render/?blocks=%5B%22authorization-link%22%2C%22loginlink%22%5D&handles=%5B%22default%22%2C%22cms_index_index.................

This request return 500 error due to the below error

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: magento->routers_match->CONTROLLER_ACTION:magento_pagecache_block_render->action_body in /vendor/smile/module-debug-toolbar/Helper/Profiler.php on line 125

Exception #0 (Exception): Notice: Undefined index: magento->routers_match->CONTROLLER_ACTION:magento_pagecache_block_render->action_body in /vendor/smile/module-debug-toolbar/Helper/Profiler.php on line 125
<pre>#1 Smile\DebugToolbar\Helper\Profiler->prepareTimers() called at [vendor/smile/module-debug-toolbar/Helper/Profiler.php:68]
#2 Smile\DebugToolbar\Helper\Profiler->computeStats() called at [vendor/smile/module-debug-toolbar/Observer/AddToolbar.php:105]
#3 Smile\DebugToolbar\Observer\AddToolbar->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#4 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#5 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/smile/module-debug-toolbar/Plugin/Event/Invoker.php:64]
#8 Smile\DebugToolbar\Plugin\Event\Invoker->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#9 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Event/Invoker/InvokerDefault/Interceptor.php:23]
#11 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#12 Magento\Framework\Event\Manager->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Magento\Framework\Event\Manager\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Magento\Framework\Event\Manager\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/smile/module-debug-toolbar/Plugin/Event/Manager.php:52]
#15 Smile\DebugToolbar\Plugin\Event\Manager->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Magento\Framework\Event\Manager\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Framework\Event\Manager\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Event/Manager/Interceptor.php:23]
#18 Magento\Framework\Event\Manager\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:131]
#19 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#23 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#24 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

**Comment by guvra** [comment]
Hi @onlinebizsoft ,

Thanks for the report.

This is fixed by commit https://github.com/Smile-SA/magento2-module-debug-toolbar/commit/0269849dfb391f0724b33c88a28d95ec3b9781cd release in 5.1.2.

Could you confirm that fixes your issue?

**Comment by onlinebizsoft** [comment]
@guvra sorry for late response. I have a chance to confirm it working now. Thank you very much.
