### ISSUE TITLE
Should allow PHP 8.2

### ISSUE THREAD

**Issue by onlinebizsoft** [Smile-SA/magento2-module-debug-toolbar#24]
Magento 2.4.6 now supports PHP 8.2 so should allow the module to use with PHP 8.2

**Comment by guvra** [comment]
What issue are you facing? 8.2 is already allowed by composer.json.

**Comment by onlinebizsoft** [comment]
@guvra sorry, maybe my bad, I'm in progress of upgrading our platform, I understand ^8.1 as >=8.1.0 <8.2.0 ?

**Comment by onlinebizsoft** [comment]
Ah I have checked the composer document again, it was changed since Composer 2.0. Closing this now.
