### ISSUE TITLE
"Class \"Smile\\DebugToolbar\\Block\\Zone\\Summary\\Interceptor\" does not exist"

### ISSUE THREAD

**Issue by Aquive** [Smile-SA/magento2-module-debug-toolbar#28]
- I installed it with `composer require --dev hyva-themes/magento2-smile-debug-toolbar `
- ran `bin/magento config:set smile_debugtoolbar/configuration/enabled 1` to enable it
- when I open a frontend page, i get below error.

`"Class \"Smile\\DebugToolbar\\Block\\Zone\\Summary\\Interceptor\" does not exist"`

**Comment by amine-y** [comment]
Hello @Aquive,

Why did you install it using `composer require --dev hyva-themes/magento2-smile-debug-toolbar`? You should use `composer require --dev smile/module-debug-toolbar` instead.

**Comment by Aquive** [comment]
Not sure, I think I got it from a guide somewhere? Thanks though.

**Comment by DmitryFurs** [comment]
Faced the same issue on Magento 2.4.5-p4

> main.CRITICAL: Type "mixed" cannot be nullable
> Class Smile\DebugToolbar\Block\Zone\Summary\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []

Fixed by https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-40/acsd-55031-type-mixed-cannot-be-nullable-error-during-compilation

```bash
./vendor/bin/magento-patches apply ACSD-55031
```
