### ISSUE TITLE
4.x is incompatible with Magento 2.2

### ISSUE THREAD

**Issue by pczerkas** [Smile-SA/magento2-module-debug-toolbar#4]
Hello,

please add documentation about incompatibilities of Smile_DebugToolbar 4.x version with older Magento 2.2 versions. Magento module:enable command does not produce sensible information when one tries to install Smile_DebugToolbar 4.x with Magento 2.2.x (missing "setup_version" attribute in etc/module.xml file).

Best regards,
Przemek

**Comment by spipu** [comment]
Sorry, it was a composer miss configuration...

Smile Debug Toolbar v4.x is for Magento 2.3
Smile Debug Toolbar v3.x is for Magento 2.2

the tags 4.0.0 and 4.0.1 has an error in the magento requirements. They have been deleted.

**Comment by pczerkas** [comment]
Thanks!
