### ISSUE TITLE
Warning: Use of undefined constant BP - assumed 'BP' (this will throw an Error in a future version of PHP) in /magento2/magento/vendor/smile/module-debug-toolbar/registration.php on line 22

### ISSUE THREAD

**Issue by mozgbrasil** [Smile-SA/magento2-module-debug-toolbar#5]
Hello good afternoon

I would like to inform you of the following

I loaded the autoloader into a new file and the alert is displayed

Warning: Use of undefined constant BP - assumed 'BP' (this will throw an Error in a future version of PHP) in /magento2/magento/vendor/smile/module-debug-toolbar/registration.php on line 22

**Comment by carylewis** [comment]
I am also seeing this after upgrading an EE system from 2.1.18 to 2.3.4?

Is there a work around?

I tried define the BP constant to '', but then the php bin/magneto program wouldn't run at all.

**Comment by guvra** [comment]
Hi,

That seems strange, the constant should be defined when the module is loaded.
It is defined in app/autoload.php:

```php
define('BP', dirname(__DIR__));
```

Did you install Magento with composer?
