### ISSUE TITLE
Deprecated Functionality for magento 2.3.1

### ISSUE THREAD

**Issue by farhangithub27** [Smile-SA/magento2-module-debug-toolbar#6]
I'm getting following issue from info tab

Deprecated Functionality: Function create_function() is deprecated in /var/www/html/magento23demo/vendor/vpietri/adm-quickdevbar/Block/Tab/Content/PhpInfo.php on line 30

I'm using magento 2.3.1
![Screenshot from 2019-06-05 12-26-28](https://user-images.githubusercontent.com/22092017/58926071-2ad12980-878d-11e9-8d89-911c5f79a070.png)

**Comment by spipu** [comment]
You are not on the good project ;)
