### ISSUE TITLE
Undefined variable on toolbar.phtml 

### ISSUE THREAD

**Issue by Verguetz** [Smile-SA/magento2-module-debug-toolbar#9]
When i try to turn it on in admin panel i caught this message. It's simple to solve...

"Notice: Undefined variable: escaper in \/var\/www\/html\/magento2\/app\/code\/Smile\/DebugToolbar\/view\/base\/templates\/toolbar.phtml on line 18"

**Comment by guvra** [comment]
We released an update that is only compatible with Magento 2.4.
There is a requirement on magento/framework 103.0.0 in composer.json.

Did you use the recommended installation method?
`composer require --dev smile/module-debug-toolbar` (do not use the `--ignore-platform-reqs` option)

Composer will automatically download and install a compatible version of the module.
